// This file is generated by bindgen
// Do not modify this file manually!

declare module 'breeze' {

export class filesystem {
	/**
     * 
     * @param path: string
     * @returns string
     */
    static readFileSync(path: string): string
}
export class test {
	static testAsync(): Promise<number>
}
}

