// This file is generated by bindgen
// Do not modify this file manually!

declare module 'breeze' {

export class filesystem {
	/**
     * 
     * @param path: string
     * @returns string
     */
    static readFileAsStringSync(path: string): string
	/**
     * 
     * @param path: string
     * @returns Promise<string>
     */
    static readFileAsString(path: string): Promise<string>
	/**
     * 
     * @param path: string
     * @param options: filesystem.ReadDirOptions | undefined
     * @returns Promise<Array<string>>
     */
    static readdir(path: string, options?: filesystem.ReadDirOptions | undefined): Promise<Array<string>>
	/**
     * 
     * @param path: string
     * @param options: filesystem.ReadDirOptions | undefined
     * @returns Array<string>
     */
    static readdirSync(path: string, options?: filesystem.ReadDirOptions | undefined): Array<string>
	/**
     * 
     * @param path: string
     * @param options: filesystem.MkDirOptions | undefined
     * @returns Promise<boolean>
     */
    static mkdir(path: string, options?: filesystem.MkDirOptions | undefined): Promise<boolean>
	/**
     * 
     * @param path: string
     * @param options: filesystem.MkDirOptions | undefined
     * @returns boolean
     */
    static mkdirSync(path: string, options?: filesystem.MkDirOptions | undefined): boolean
	/**
     * 
     * @param path: string
     * @returns boolean
     */
    static exists(path: string): boolean
	/**
     * 
     * @param path: string
     * @param options: filesystem.RmOptions | undefined
     * @returns Promise<boolean>
     */
    static rm(path: string, options?: filesystem.RmOptions | undefined): Promise<boolean>
	/**
     * 
     * @param path: string
     * @param options: filesystem.RmOptions | undefined
     * @returns boolean
     */
    static rmSync(path: string, options?: filesystem.RmOptions | undefined): boolean
	/**
     * 
     * @param path: string
     * @param content: string
     * @returns Promise<boolean>
     */
    static writeStringToFile(path: string, content: string): Promise<boolean>
}
namespace filesystem {
export class ReadDirOptions {
	recursive: boolean
	follow_symlinks: boolean
}
}
namespace filesystem {
export class MkDirOptions {
	recursive: boolean
}
}
namespace filesystem {
export class RmOptions {
	recursive: boolean
}
}
export class infra {
	/**
     * 
     * @param ms: number
     * @returns Promise<void>
     */
    static sleep(ms: number): Promise<void>
	/**
     *  This is a blocking sleep, not recommended in JS context
     *  Use sleep() instead for non-blocking sleep
     * @param ms: number
     * @returns void
     */
    static sleepSync(ms: number): void
	/**
     *  Breeze uses a low resolution timer (30ms) for setTimeout and setInterval
     *  due to performance concerns.
     *  Use sleep() for more precise timing if needed.
     * @param callback: (() => void)
     * @param ms: number
     * @returns number
     */
    static setTimeout(callback: (() => void), ms: number): number
	/**
     *  Breeze uses a low resolution timer (30ms) for setTimeout and setInterval
     *  due to performance concerns.
     *  Use sleep() for more precise timing if needed.
     * @param callback: (() => void)
     * @param ms: number
     * @returns number
     */
    static setInterval(callback: (() => void), ms: number): number
	/**
     * 
     * @param id: number
     * @returns void
     */
    static clearTimeout(id: number): void
	/**
     * 
     * @param id: number
     * @returns void
     */
    static clearInterval(id: number): void
	/**
     * 
     * @param base64: string
     * @returns string
     */
    static atob(base64: string): string
	/**
     * 
     * @param str: string
     * @returns string
     */
    static btoa(str: string): string
}
export class test {
	static testAsync(): Promise<number>
}
}

