// This file is generated by bindgen
// Do not modify this file manually!

declare module 'breeze' {

export class Blob {
	/**
     *  size of the blob in bytes
     */
    get size(): number;
	/**
     *  MIME type of the blob
     */
    get type(): string;
	/**
     *  Returns the blob data as an ArrayBuffer
      @returns ArrayBuffer
     */
    arrayBuffer(): ArrayBuffer
	/**
     *  Returns the blob data decoded as a UTF-8 string
      @returns string
     */
    text(): string
	/**
     *  Returns a new Blob that is a subset of this Blob
     * @param start: number | undefined
     * @param end: number | undefined
     * @param contentType: string | undefined
     * @returns Blob
     */
    slice(start?: number | undefined, end?: number | undefined, contentType?: string | undefined): Blob
}
export class filesystem {
	/**
     * 
     * @param path: string
     * @returns string
     */
    static readFileAsStringSync(path: string): string
	/**
     * 
     * @param path: string
     * @returns Promise<string>
     */
    static readFileAsString(path: string): Promise<string>
	/**
     * 
     * @param path: string
     * @param options: filesystem.ReadDirOptions | undefined
     * @returns Promise<Array<string>>
     */
    static readdir(path: string, options?: filesystem.ReadDirOptions | undefined): Promise<Array<string>>
	/**
     * 
     * @param path: string
     * @param options: filesystem.ReadDirOptions | undefined
     * @returns Array<string>
     */
    static readdirSync(path: string, options?: filesystem.ReadDirOptions | undefined): Array<string>
	/**
     * 
     * @param path: string
     * @param options: filesystem.MkDirOptions | undefined
     * @returns Promise<boolean>
     */
    static mkdir(path: string, options?: filesystem.MkDirOptions | undefined): Promise<boolean>
	/**
     * 
     * @param path: string
     * @param options: filesystem.MkDirOptions | undefined
     * @returns boolean
     */
    static mkdirSync(path: string, options?: filesystem.MkDirOptions | undefined): boolean
	/**
     * 
     * @param path: string
     * @returns boolean
     */
    static exists(path: string): boolean
	/**
     * 
     * @param path: string
     * @param options: filesystem.RmOptions | undefined
     * @returns Promise<boolean>
     */
    static rm(path: string, options?: filesystem.RmOptions | undefined): Promise<boolean>
	/**
     * 
     * @param path: string
     * @param options: filesystem.RmOptions | undefined
     * @returns boolean
     */
    static rmSync(path: string, options?: filesystem.RmOptions | undefined): boolean
	/**
     * 
     * @param path: string
     * @param content: string
     * @returns Promise<boolean>
     */
    static writeStringToFile(path: string, content: string): Promise<boolean>
	/**
     *  Binary file I/O (returns/accepts ArrayBuffer on JS side)
     * @param path: string
     * @returns ArrayBuffer
     */
    static readFileSync(path: string): ArrayBuffer
	/**
     * 
     * @param path: string
     * @returns Promise<ArrayBuffer>
     */
    static readFile(path: string): Promise<ArrayBuffer>
	/**
     * 
     * @param path: string
     * @param content: ArrayBuffer
     * @returns Promise<boolean>
     */
    static writeFile(path: string, content: ArrayBuffer): Promise<boolean>
}
namespace filesystem {
export class ReadDirOptions {
	recursive: boolean
	follow_symlinks: boolean
}
}
namespace filesystem {
export class MkDirOptions {
	recursive: boolean
}
}
namespace filesystem {
export class RmOptions {
	recursive: boolean
}
}
export class http {
	/**
     *  Fetch a URL and return a Response
     * @param url: string
     * @param init: http.RequestInit | undefined
     * @returns Promise<Response>
     */
    static fetch(url: string, init?: http.RequestInit | undefined): Promise<Response>
}
namespace http {
export class Headers {
	list: Array<[string, string]>
	/**
     * 
     * @param name: string
     * @returns string
     */
    get(name: string): string
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    set(name: string, value: string): void
	/**
     * 
     * @param name: string
     * @returns boolean
     */
    has(name: string): boolean
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    append(name: string, value: string): void
	/**
     *  Note: named 'remove_' to avoid conflict with C macro 'remove'
     * @param name: string
     * @returns void
     */
    remove_(name: string): void
}
}
namespace http {
export class Response {
	get status(): number;
	get statusText(): string;
	get ok(): boolean;
	get url(): string;
	get headers(): http.Headers;
	/**
     *  Returns body decoded as UTF-8 string
      @returns string
     */
    text(): string
	/**
     *  Returns body as ArrayBuffer
      @returns ArrayBuffer
     */
    arrayBuffer(): ArrayBuffer
	/**
     *  Returns body as JSON string (caller can JSON.parse on JS side)
      @returns string
     */
    json_text(): string
	json(): any
	blob(): Blob
}
}
namespace http {
export class RequestInit {
	method: string
	/**
     *  body can be a string or an ArrayBuffer (binary data)
     */
    body?: string | ArrayBuffer | Blob | undefined
	/**
     *  headers: accepts plain object {key: value}
     */
    headers?: std.map<string, string> | undefined
}
}
export class infra {
	/**
     * 
     * @param ms: number
     * @returns Promise<void>
     */
    static sleep(ms: number): Promise<void>
	/**
     *  This is a blocking sleep, not recommended in JS context
     *  Use sleep() instead for non-blocking sleep
     * @param ms: number
     * @returns void
     */
    static sleepSync(ms: number): void
	/**
     *  Breeze uses a low resolution timer (30ms) for setTimeout and setInterval
     *  due to performance concerns.
     *  Use sleep() for more precise timing if needed.
     * @param callback: (() => void)
     * @param ms: number
     * @returns number
     */
    static setTimeout(callback: (() => void), ms: number): number
	/**
     *  Breeze uses a low resolution timer (30ms) for setTimeout and setInterval
     *  due to performance concerns.
     *  Use sleep() for more precise timing if needed.
     * @param callback: (() => void)
     * @param ms: number
     * @returns number
     */
    static setInterval(callback: (() => void), ms: number): number
	/**
     * 
     * @param id: number
     * @returns void
     */
    static clearTimeout(id: number): void
	/**
     * 
     * @param id: number
     * @returns void
     */
    static clearInterval(id: number): void
	/**
     * 
     * @param base64: string
     * @returns string
     */
    static atob(base64: string): string
	/**
     * 
     * @param str: string
     * @returns string
     */
    static btoa(str: string): string
}
namespace infra {
export class URLSearchParams {
	list: Array<[string, string]>
	size(): number
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    append(name: string, value: string): void
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    remove(name: string, value: string): void
	/**
     * 
     * @param name: string
     * @returns string
     */
    get(name: string): string
	/**
     * 
     * @param name: string
     * @returns Array<string>
     */
    getAll(name: string): Array<string>
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns boolean
     */
    has(name: string, value: string): boolean
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    set(name: string, value: string): void
	sort(): void
	toString(): string
}
}
namespace infra {
export class URL {
	get href(): string;
    set href(value: string);
	get protocol(): string;
    set protocol(value: string);
	get username(): string;
    set username(value: string);
	get password(): string;
    set password(value: string);
	get host(): string;
    set host(value: string);
	get hostname(): string;
    set hostname(value: string);
	get port(): string;
    set port(value: string);
	get pathname(): string;
    set pathname(value: string);
	get search(): string;
    set search(value: string);
	get searchParams(): infra.URLSearchParams;
	get hash(): string;
    set hash(value: string);
	/**
     * 
     * @param url_string: string
     * @returns infra.URL
     */
    static parse(url_string: string): infra.URL
	/**
     * 
     * @param url_string: string
     * @returns boolean
     */
    static canParse(url_string: string): boolean
	origin(): string
	toJSON(): string
}
}
export class test {
	static testAsync(): Promise<number>
}
}

