// This file is generated by bindgen
// Do not modify this file manually!

declare module 'breeze' {

export class filesystem {
	/**
     * 
     * @param path: string
     * @returns string
     */
    static readFileAsStringSync(path: string): string
	/**
     * 
     * @param path: string
     * @returns Promise<string>
     */
    static readFileAsString(path: string): Promise<string>
	/**
     * 
     * @param path: string
     * @param options: filesystem.ReadDirOptions | undefined
     * @returns Promise<Array<string>>
     */
    static readdir(path: string, options?: filesystem.ReadDirOptions | undefined): Promise<Array<string>>
	/**
     * 
     * @param path: string
     * @param options: filesystem.ReadDirOptions | undefined
     * @returns Array<string>
     */
    static readdirSync(path: string, options?: filesystem.ReadDirOptions | undefined): Array<string>
	/**
     * 
     * @param path: string
     * @param options: filesystem.MkDirOptions | undefined
     * @returns Promise<boolean>
     */
    static mkdir(path: string, options?: filesystem.MkDirOptions | undefined): Promise<boolean>
	/**
     * 
     * @param path: string
     * @param options: filesystem.MkDirOptions | undefined
     * @returns boolean
     */
    static mkdirSync(path: string, options?: filesystem.MkDirOptions | undefined): boolean
	/**
     * 
     * @param path: string
     * @returns boolean
     */
    static exists(path: string): boolean
	/**
     * 
     * @param path: string
     * @param options: filesystem.RmOptions | undefined
     * @returns Promise<boolean>
     */
    static rm(path: string, options?: filesystem.RmOptions | undefined): Promise<boolean>
	/**
     * 
     * @param path: string
     * @param options: filesystem.RmOptions | undefined
     * @returns boolean
     */
    static rmSync(path: string, options?: filesystem.RmOptions | undefined): boolean
	/**
     * 
     * @param path: string
     * @param content: string
     * @returns Promise<boolean>
     */
    static writeStringToFile(path: string, content: string): Promise<boolean>
}
namespace filesystem {
export class ReadDirOptions {
	recursive: boolean
	follow_symlinks: boolean
}
}
namespace filesystem {
export class MkDirOptions {
	recursive: boolean
}
}
namespace filesystem {
export class RmOptions {
	recursive: boolean
}
}
export class infra {
	/**
     * 
     * @param ms: number
     * @returns Promise<void>
     */
    static sleep(ms: number): Promise<void>
	/**
     *  This is a blocking sleep, not recommended in JS context
     *  Use sleep() instead for non-blocking sleep
     * @param ms: number
     * @returns void
     */
    static sleepSync(ms: number): void
	/**
     *  Breeze uses a low resolution timer (30ms) for setTimeout and setInterval
     *  due to performance concerns.
     *  Use sleep() for more precise timing if needed.
     * @param callback: (() => void)
     * @param ms: number
     * @returns number
     */
    static setTimeout(callback: (() => void), ms: number): number
	/**
     *  Breeze uses a low resolution timer (30ms) for setTimeout and setInterval
     *  due to performance concerns.
     *  Use sleep() for more precise timing if needed.
     * @param callback: (() => void)
     * @param ms: number
     * @returns number
     */
    static setInterval(callback: (() => void), ms: number): number
	/**
     * 
     * @param id: number
     * @returns void
     */
    static clearTimeout(id: number): void
	/**
     * 
     * @param id: number
     * @returns void
     */
    static clearInterval(id: number): void
	/**
     * 
     * @param base64: string
     * @returns string
     */
    static atob(base64: string): string
	/**
     * 
     * @param str: string
     * @returns string
     */
    static btoa(str: string): string
}
namespace infra {
export class URLSearchParams {
	list: Array<[string, string]>
	size(): number
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    append(name: string, value: string): void
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    remove(name: string, value: string): void
	/**
     * 
     * @param name: string
     * @returns string
     */
    get(name: string): string
	/**
     * 
     * @param name: string
     * @returns Array<string>
     */
    getAll(name: string): Array<string>
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns boolean
     */
    has(name: string, value: string): boolean
	/**
     * 
     * @param name: string
     * @param value: string
     * @returns void
     */
    set(name: string, value: string): void
	sort(): void
	toString(): string
}
}
namespace infra {
export class URL {
	get href(): string;
    set href(value: string);
	get protocol(): string;
    set protocol(value: string);
	get username(): string;
    set username(value: string);
	get password(): string;
    set password(value: string);
	get host(): string;
    set host(value: string);
	get hostname(): string;
    set hostname(value: string);
	get port(): string;
    set port(value: string);
	get pathname(): string;
    set pathname(value: string);
	get search(): string;
    set search(value: string);
	get searchParams(): infra.URLSearchParams;
	get hash(): string;
    set hash(value: string);
	/**
     * 
     * @param url_string: string
     * @returns infra.URL
     */
    static parse(url_string: string): infra.URL
	/**
     * 
     * @param url_string: string
     * @returns boolean
     */
    static canParse(url_string: string): boolean
	origin(): string
	toJSON(): string
}
}
export class test {
	static testAsync(): Promise<number>
}
}

