// This file is generated by bindgen
// Do not modify this file manually!

#pragma once
#include "binding_types.h" // Assuming this will be in the same output directory
#include "quickjs.h"
#include "quickjspp.hpp"

template <typename T>
struct js_bind {
    static void bind(qjs::Context::Module &mod) {}
};

inline void bindAll(qjs::Context::Module &mod) {

}
