name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          # use newer version of g++ and libstdc++
          sudo apt-get install -y g++-15 libstdc++-15-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/c++-15 100

          xmake f -y

      - name: Configure
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: xmake f -y

      - name: Build
        run: xmake build -y -v
