name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          version: master 

      - name: Configure
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          xmake f -y --toolchain=zig

      - name: Configure
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: xmake f -y

      - name: Build
        run: xmake build -y -v
