name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          # we must use libstdcxx >= 13 and clang >=18 for the latest C++ standard
          sudo apt-get update
          sudo apt-get install -y libstdc++-13-dev clang-21
          sudo ln -s /usr/bin/clang-21 /usr/bin/clang
          sudo ln -s /usr/bin/clang++-21 /usr/bin/clang++
          
          xmake f -y --toolchain=clang

      - name: Configure
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: xmake f -y

      - name: Build
        run: xmake build -y -v
